/* AUTH ACTIONS */
export const AUTH_STATE_BUSY = "AUTH_STATE_BUSY"
export const AUTH_STATE_FAILED = "AUTH_STATE_FAILED"
export const AUTH_STATE_SUCCESS = "AUTH_STATE_SUCCESS"
export const AUTH_STATE_EDIT_BUSY = "AUTH_STATE_EDIT_BUSY"
export const AUTH_STATE_EDIT_SUCCESS = "AUTH_STATE_EDIT_SUCCESS"
export const AUTH_STATE_EDIT_FAILED = "AUTH_STATE_EDIT_FAILED"

/* PETS ACTIONS */
export const PETS_ADD_SUCCESS = "PETS_ADD_SUCCESS"
export const PETS_ADD_BUSY = "PETS_ADD_BUSY"
export const PETS_ADD_FAILED = "PETS_ADD_FAILED"

/* POSTS ACTIONS */
export const POST_ADD_SUCCESS = "POST_ADD_SUCCESS"
export const POST_ADD_BUSY = "POST_ADD_BUSY"
export const POST_ADD_FAILED = "POST_ADD_FAILED"
export const POSTS_FETCH_SUCCESS = "POSTS_FETCH_SUCCESS"
export const POSTS_FETCH_BUSY = "POSTS_FETCH_BUSY"
export const POSTS_FETCH_FAILED = "POSTS_FETCH_FAILED"
export const POST_LIKE_SUCCESS = "POST_LIKE_SUCCESS"
export const POSTS_PULL_SUCCESS = "POSTS_PULL_SUCCESS"

/* PRODUCT ACTIONS*/

export const PRODUCTS_FETCH_SUCCESS = "PRODUCTS_FETCH_SUCCESS"
export const PRODUCTS_FETCH_BUSY = "PRODUCTS_FETCH_BUSY"
export const PRODUCTS_FETCH_FAILED = "PRODUCTS_FETCH_FAILED"

/* PRODUCT DETAILS ACTIONS*/

export const PRODUCT_DETAILS_FETCH_SUCCESS = "PRODUCT_DETAILS_FETCH_SUCCESS"
export const PRODUCT_DETAILS_FETCH_BUSY = "PRODUCT_DETAILS_FETCH_BUSY"
export const PRODUCT_DETAILS_FETCH_FAILED = "PRODUCT_DETAILS_FETCH_FAILED"

/*CATEGORY ACTIONS*/
export const CATEGORY_FETCH_SUCCESS = "CATEGORY_FETCH_SUCCESS"
export const CATEGORY_FETCH_BUSY = "CATEGORY_FETCH_BUSY"
export const CATEGORY_FETCH_FAILED = "CATEGORY_FETCH_FAILED"

/*CArt ACTIONS*/

export const PRODUCT_CART_ADD_BUSY = "PRODUCT_CART_ADD_BUSY"
export const PRODUCT_CART_ADD_FAILED = "PRODUCT_CART_ADD_FAILED"
export const PRODUCT_CART_ADD_SUCCESS = "PRODUCT_CART_ADD_SUCCESS"

export const PRODUCT_CART_FETCH_SUCCESS = "PRODUCT_CART_FETCH_SUCCESS"
export const PRODUCT_CART_FETCH_BUSY = "PRODUCT_CART_FETCH_BUSY"
export const PRODUCT_CART_FETCH_FAILED = "PRODUCT_CART_FETCH_FAILED"

export const PRODUCT_CART_DELETE_SUCCESS = "PRODUCT_CART_DELETE_SUCCESS"
export const PRODUCT_CART_DELETE_BUSY = "PRODUCT_CART_DELETE_BUSY"
export const PRODUCT_CART_DELETE_FAILED = "PRODUCT_CART_DELETE_FAILED"

export const PRODUCT_CART_ADDRESSUPDATE_SUCCESS = "PRODUCT_CART_ADDRESSUPDATE_SUCCESS"
export const PRODUCT_CART_ADDRESSUPDATE_BUSY = "PRODUCT_CART_ADDRESSUPDATE_BUSY"
export const PRODUCT_CART_ADDRESSUPDATE_FAILED = "PRODUCT_CART_ADDRESSUPDATE_FAILED"

export const PRODUCT_ORDER_SUCCESS = "PRODUCT_ORDER_SUCCESS"
export const PRODUCT_ORDER_BUSY = "PRODUCT_ORDER_BUSY"
export const PRODUCT_ORDER_FAILED = "PRODUCT_ORDER_FAILED"

/*ORDER ACTIONS*/
export const ORDER_FETCH_SUCCESS = "ORDER_FETCH_SUCCESS"
export const ORDER_FETCH_BUSY = "ORDER_FETCH_BUSY"
export const ORDER_FETCH_FAILED = "ORDER_FETCH_FAILED"

/*ORDERDETAILS ACTIONS*/
export const ORDERDETAILS_FETCH_SUCCESS = "ORDERDETAILS_FETCH_SUCCESS"
export const ORDERDETAILS_FETCH_BUSY = "ORDERDETAILS_FETCH_BUSY"
export const ORDERDETAILS_FETCH_FAILED = "ORDERDETAILS_FETCH_FAILED"