/* AUTH ACTIONS */
export const AUTH_STATE_BUSY = "AUTH_STATE_BUSY"
export const AUTH_STATE_FAILED = "AUTH_STATE_FAILED"
export const AUTH_STATE_SUCCESS = "AUTH_STATE_SUCCESS"
export const AUTH_STATE_EDIT_BUSY = "AUTH_STATE_EDIT_BUSY"
export const AUTH_STATE_EDIT_SUCCESS = "AUTH_STATE_EDIT_SUCCESS"
export const AUTH_STATE_EDIT_FAILED = "AUTH_STATE_EDIT_FAILED"

/* PETS ACTIONS */
export const PETS_ADD_SUCCESS = "PETS_ADD_SUCCESS"
export const PETS_ADD_BUSY = "PETS_ADD_BUSY"
export const PETS_ADD_FAILED = "PETS_ADD_FAILED"

/* POSTS ACTIONS */
export const POST_ADD_SUCCESS = "POST_ADD_SUCCESS"
export const POST_ADD_BUSY = "POST_ADD_BUSY"
export const POST_ADD_FAILED = "POST_ADD_FAILED"
export const POSTS_FETCH_SUCCESS = "POSTS_FETCH_SUCCESS"
export const POSTS_FETCH_BUSY = "POSTS_FETCH_BUSY"
export const POSTS_FETCH_FAILED = "POSTS_FETCH_FAILED"
export const POST_LIKE_SUCCESS = "POST_LIKE_SUCCESS"
export const POSTS_PULL_SUCCESS = "POSTS_PULL_SUCCESS"

/* PRODUCT ACTIONS*/

export const PRODUCTS_FETCH_SUCCESS = "PRODUCTS_FETCH_SUCCESS"
export const PRODUCTS_FETCH_BUSY = "PRODUCTS_FETCH_BUSY"
export const PRODUCTS_FETCH_FAILED = "PRODUCTS_FETCH_FAILED"
export const CATEGORY_FETCH_SUCCESS = "CATEGORY_FETCH_SUCCESS"
export const CATEGORY_FETCH_BUSY = "CATEGORY_FETCH_BUSY"
export const CATEGORY_FETCH_FAILED = "CATEGORY_FETCH_FAILED"